# Generated by Django 3.1.10 on 2021-11-22 11:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutServiceInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        unique=True,
                        verbose_name="The order in which the link is displayed",
                    ),
                ),
                (
                    "link_text_fr",
                    models.CharField(max_length=255, verbose_name="The link text"),
                ),
                (
                    "link_text_en",
                    models.CharField(max_length=255, verbose_name="The link text"),
                ),
                (
                    "link_url_fr",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Domain name must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="The link URL to the page containing the information",
                    ),
                ),
                (
                    "link_url_en",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Domain name must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="The link URL to the page containing the information",
                    ),
                ),
            ],
            options={
                "verbose_name": "About service information",
                "verbose_name_plural": "About service informations",
            },
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "email_fr",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "email_en",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "phone_number_fr",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must have 9 to 15 digits, and can be preceded by + sign.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "phone_number_en",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must have 9 to 15 digits, and can be preceded by + sign.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "website_fr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Domain name must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "website_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Domain name must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="Website URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company information",
                "verbose_name_plural": "Mediation requests",
            },
        ),
    ]
