# Generated by Django 3.1.10 on 2021-11-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinformation",
            options={
                "verbose_name": "Company information",
                "verbose_name_plural": "Company information",
            },
        ),
        migrations.RemoveField(
            model_name="contactinformation",
            name="_singleton",
        ),
        migrations.RemoveField(
            model_name="contactinformation",
            name="created",
        ),
        migrations.RemoveField(
            model_name="contactinformation",
            name="modified",
        ),
    ]
