# Generated by Django 3.1.10 on 2021-11-22 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0003_aboutserviceinformation_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutserviceinformation",
            name="link_url_en",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="URL must be valid, eg. http://domain.extension",
                        regex="^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                    )
                ],
                verbose_name="The link URL to the page containing the information",
            ),
        ),
        migrations.AlterField(
            model_name="aboutserviceinformation",
            name="link_url_fr",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="URL must be valid, eg. http://domain.extension",
                        regex="^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                    )
                ],
                verbose_name="The link URL to the page containing the information",
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="website_en",
            field=models.CharField(
                blank=True,
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="URL must be valid, eg. http://domain.extension",
                        regex="^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                    )
                ],
                verbose_name="Website URL",
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="website_fr",
            field=models.CharField(
                blank=True,
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        message="URL must be valid, eg. http://domain.extension",
                        regex="^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                    )
                ],
                verbose_name="Website URL",
            ),
        ),
    ]
