# Generated by Django 3.1.10 on 2021-11-23 09:29

import connect_access.configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_auto_20211122_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutserviceinformation",
            name="display_order",
            field=models.IntegerField(
                default=connect_access.configuration.models.display_order_default,
                unique=True,
                verbose_name="The order in which the link is displayed",
            ),
        ),
    ]
