# Generated by Django 3.1.10 on 2021-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0005_auto_20211123_1029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutserviceinformation",
            options={
                "verbose_name": "About mediation service information",
                "verbose_name_plural": "About mediation service information",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinformation",
            options={
                "verbose_name": "Information about the organization running the mediation service",
                "verbose_name_plural": "Information about the organization running the mediation service",
            },
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="email_text_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Email address display text"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="email_text_fr",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Email address display text"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="phone_number_text_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Phone number display text"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="phone_number_text_fr",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Phone number display text"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="website_text_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Website display text"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="website_text_fr",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Website display text"
            ),
        ),
    ]
