# Generated by Django 3.1.10 on 2022-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0006_auto_20211123_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="terms_of_servce_en",
            field=models.TextField(
                blank=True, verbose_name="Terms of service (please use Markdown format)"
            ),
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="terms_of_servce_fr",
            field=models.TextField(
                blank=True, verbose_name="Terms of service (please use Markdown format)"
            ),
        ),
    ]
