# Generated by Django 3.1.10 on 2022-02-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0007_auto_20220209_1431"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinformation",
            old_name="terms_of_servce_en",
            new_name="terms_of_service_en",
        ),
        migrations.RenameField(
            model_name="contactinformation",
            old_name="terms_of_servce_fr",
            new_name="terms_of_service_fr",
        ),
    ]
