# Generated by Django 3.1.10 on 2022-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0008_auto_20220210_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="terms_of_service_en",
            field=models.TextField(
                blank=True,
                verbose_name="Terms of service. Please use Markdown format, and start headings from level 2 (eg. '## My heading')",
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="terms_of_service_fr",
            field=models.TextField(
                blank=True,
                verbose_name="Terms of service. Please use Markdown format, and start headings from level 2 (eg. '## My heading')",
            ),
        ),
    ]
