# Generated by Django 3.1.10 on 2022-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0009_auto_20220214_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutserviceinformation",
            name="link_url_en",
            field=models.CharField(
                max_length=200,
                verbose_name="The link URL to the page containing the information",
            ),
        ),
        migrations.AlterField(
            model_name="aboutserviceinformation",
            name="link_url_fr",
            field=models.CharField(
                max_length=200,
                verbose_name="The link URL to the page containing the information",
            ),
        ),
    ]
