# Generated by Django 3.0.11 on 2020-12-10 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20201115_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must have 9 to 15 digits, and can be preceded by + sign.",
                        regex="^\\+?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, max_length=255, verbose_name="Surname"),
        ),
    ]
