# Generated by Django 3.1.10 on 2021-09-30 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20210601_1400"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="surname",
            new_name="last_name",
        ),
    ]
