# Generated by Django 4.0.8 on 2023-07-11 12:05

import django.core.validators
from django.db import migrations

import connect_access.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20210930_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=connect_access.models.fields.PhoneNumberField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must have 8 to 15 digits, and can be preceded by + sign.",
                        regex="^\\+?\\d{8,15}$",
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
    ]
