version: "3.8"

volumes:
  staging_postgres_data: {}
  staging_postgres_data_backups: {}
  staging_traefik: {}
  staging_django_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: connect_access_django:staging
    volumes:
      - staging_django_media:/app/backend/connect_access/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.staging/.data
      - ./.envs/.staging/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: connect_access_postgres:staging
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data:Z
      - staging_postgres_data_backups:/backups:z
      - ./compose/production/postgres/init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.envs/.staging/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: connect_access_traefik:staging
    depends_on:
      - django
    labels:
      - "traefik.enable=true"
    volumes:
      - staging_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:${APPLICATION_PORT}:80"
      - "0.0.0.0:${FLOWER_PORT}:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: connect_access_celeryworker:staging
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: connect_access_celerybeat:staging
    command: /start-celerybeat

  flower:
    <<: *django
    image: connect_access_flower:staging
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: connect_access_nginx:staging
    depends_on:
      - django
    volumes:
      - staging_django_media:/usr/share/nginx/media:ro
