# Generated by Django 4.0.8 on 2023-07-11 12:05

import uuid

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import connect_access.apps.configuration.abstract_models
import connect_access.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutServiceInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Public identifier",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=connect_access.apps.configuration.abstract_models.display_order_default,
                        unique=True,
                        verbose_name="The order in which the link is displayed",
                    ),
                ),
                (
                    "link_text_fr",
                    models.CharField(max_length=255, verbose_name="The link text"),
                ),
                (
                    "link_text_en",
                    models.CharField(max_length=255, verbose_name="The link text"),
                ),
                (
                    "link_url_fr",
                    models.CharField(
                        max_length=200,
                        verbose_name="The link URL to the page containing the information",
                    ),
                ),
                (
                    "link_url_en",
                    models.CharField(
                        max_length=200,
                        verbose_name="The link URL to the page containing the information",
                    ),
                ),
            ],
            options={
                "verbose_name": "About mediation service information",
                "verbose_name_plural": "About mediation service information",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_fr",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "email_en",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "email_text_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Email address display text",
                    ),
                ),
                (
                    "email_text_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Email address display text",
                    ),
                ),
                (
                    "phone_number_fr",
                    connect_access.models.fields.PhoneNumberField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must have 8 to 15 digits, and can be preceded by + sign.",
                                regex="^\\+?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "phone_number_en",
                    connect_access.models.fields.PhoneNumberField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must have 8 to 15 digits, and can be preceded by + sign.",
                                regex="^\\+?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "phone_number_text_fr",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Phone number display text",
                    ),
                ),
                (
                    "phone_number_text_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Phone number display text",
                    ),
                ),
                (
                    "website_fr",
                    connect_access.models.fields.DomainNameField(
                        blank=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="URL must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z-1-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "website_en",
                    connect_access.models.fields.DomainNameField(
                        blank=True,
                        max_length=200,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="URL must be at least in the form domain.extension",
                                regex="^(https?:\\/\\/)?(www\\.)?[-a-zA-Z-1-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)$",
                            )
                        ],
                        verbose_name="Website URL",
                    ),
                ),
                (
                    "website_text_fr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Website display text"
                    ),
                ),
                (
                    "website_text_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Website display text"
                    ),
                ),
                (
                    "terms_of_service_fr",
                    models.TextField(
                        blank=True,
                        verbose_name="Terms of service. Please use Markdown format.",
                    ),
                ),
                (
                    "terms_of_service_en",
                    models.TextField(
                        blank=True,
                        verbose_name="Terms of service. Please use Markdown format.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Information about the organization running the mediation service",
                "verbose_name_plural": "Information about the organization running the mediation service",
                "abstract": False,
            },
        ),
    ]
