echo "Creating user and database $POSTGRES_DB_END_TO_END"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $POSTGRES_DB_END_TO_END;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB_END_TO_END TO $POSTGRES_USER;
