# Generated by Django 3.0.11 on 2021-02-17 16:52

from django.db import migrations, models
import koenaconnect.mediations.models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="attached_file",
            field=models.FileField(
                blank=True, upload_to=koenaconnect.mediations.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="organization_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="Email address of the organization",
            ),
        ),
    ]
