# Generated by Django 3.0.11 on 2021-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0002_auto_20210217_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="assistive_technology_used",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kb", "Keyboard"),
                    ("sv", "Screen reader with vocal synthesis"),
                    ("bd", "Braille display"),
                    ("zs", "Zoom software"),
                    ("vc", "Vocal command software"),
                    ("ds", "DYS Disorder software"),
                    ("vk", "Virtual keyboard"),
                    ("an", "Adapted navigation dispositive"),
                    ("ot", "Other"),
                    ("", "Blank field"),
                ],
                max_length=2,
                verbose_name="Assistive technology used",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="browser",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ff", "Firefox"),
                    ("ch", "Chrome"),
                    ("ie", "Internet Explorer"),
                    ("me", "Microsoft Edge"),
                    ("ot", "Other"),
                    ("dn", "Don't know"),
                    ("", "Blank field"),
                ],
                max_length=2,
                verbose_name="Browser",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="browser_used",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether the problem occured while using a web browser",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="did_organization_reply",
            field=models.BooleanField(
                null=True, verbose_name="Whether the organization replied"
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="did_tell_organization",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether the organization was told about the problem",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="inaccessibility_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ia", "Impossible access"),
                    ("ad", "Access possible by bypass but difficult"),
                    (
                        "ra",
                        "Random access, sometimes it works and sometimes it does not",
                    ),
                    ("", "Blank field"),
                ],
                max_length=2,
                verbose_name="Inaccessibility level",
            ),
        ),
    ]
