# Generated by Django 3.1.8 on 2021-04-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0006_auto_20210420_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediationrequest",
            name="urgent",
            field=models.BooleanField(
                default=False,
                verbose_name="Whether the request is urgent and has to be handled as quick as possible",
            ),
        ),
    ]
