# Generated by Django 3.1.8 on 2021-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0007_mediationrequest_urgent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediationrequest",
            name="urgent",
        ),
        migrations.AddField(
            model_name="mediationrequest",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ia", "Impossible access"),
                    ("ad", "Access possible by bypass but difficult"),
                    (
                        "ra",
                        "Random access, sometimes it works and sometimes it does not",
                    ),
                ],
                max_length=2,
                verbose_name="Whether the request is urgent and has to be handled as quick as possible",
            ),
        ),
    ]
