# Generated by Django 3.1.10 on 2021-05-31 10:03
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0015_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
