# Generated by Django 3.1.10 on 2021-06-01 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0016_remove_uuid_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediationrequest",
            options={
                "verbose_name": "Mediation request",
                "verbose_name_plural": "Mediation requests",
            },
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Public identifier",
            ),
        ),
    ]
