# Generated by Django 3.1.10 on 2021-08-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0023_auto_20210819_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="technology_name",
            field=models.TextField(blank=True, verbose_name="Technology name"),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="technology_version",
            field=models.TextField(blank=True, verbose_name="Technology version"),
        ),
    ]
