# Generated by Django 3.1.10 on 2021-08-20 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import koenaconnect.mediations.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0024_auto_20210820_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="assistive_technology_used",
            field=koenaconnect.mediations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("kb", "Keyboard"),
                        ("sv", "Screen reader with vocal synthesis"),
                        ("bd", "Braille display"),
                        ("zs", "Zoom software"),
                        ("vc", "Vocal command software"),
                        ("ds", "DYS Disorder software"),
                        ("vk", "Virtual keyboard"),
                        ("an", "Adapted navigation dispositive"),
                        ("ek", "Exclusive keyboard navigation"),
                        ("ot", "Other"),
                    ],
                    max_length=2,
                    verbose_name="Assistive technology used",
                ),
                default=list,
                size=None,
                verbose_name="Assistive technologies used",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="technology_name",
            field=models.TextField(blank=True, verbose_name="Technology name(s)"),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="technology_version",
            field=models.TextField(blank=True, verbose_name="Technology version(s)"),
        ),
        migrations.CreateModel(
            name="TraceReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Public identifier",
                    ),
                ),
                (
                    "trace_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ca", "Call"),
                            ("ma", "E-mail"),
                            ("le", "Letter"),
                            ("ie", "Internal exchange"),
                        ],
                        max_length=2,
                        verbose_name="The contact type",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        verbose_name="The main text describing what has happened during the contact",
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        blank=True,
                        upload_to=koenaconnect.mediations.models.trace_directory_path,
                        verbose_name="Attached file",
                    ),
                ),
                (
                    "mediation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mediations.mediationrequest",
                        verbose_name="The mediation request to which this trace is linked",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace report",
                "verbose_name_plural": "Trace reports",
            },
        ),
    ]
