# Generated by Django 3.1.10 on 2021-09-30 09:51

from django.db import migrations, models
import koenaconnect.mediations.models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0028_auto_20210920_1802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="assistive_technology_used",
            field=koenaconnect.mediations.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("kb", "Keyboard"),
                        ("sv", "Screen reader with vocal synthesis"),
                        ("bd", "Braille display"),
                        ("zs", "Zoom software"),
                        ("vc", "Vocal command software"),
                        ("ds", "DYS Disorder software"),
                        ("vk", "Virtual keyboard"),
                        ("an", "Adapted navigation dispositive"),
                        ("ek", "Exclusive keyboard navigation"),
                        ("ot", "Other"),
                    ],
                    max_length=2,
                    verbose_name="Assistive technology used",
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Assistive technologies used",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email address"
            ),
        ),
    ]
