#!/bin/bash

set -o errexit
set -o nounset


cd backend && celery \
    --app=config.celery_app \
    --broker="${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
