# Generated by Django 3.0.11 on 2021-03-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0003_auto_20210222_1100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="assistive_technology_used",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kb", "Keyboard"),
                    ("sv", "Screen reader with vocal synthesis"),
                    ("bd", "Braille display"),
                    ("zs", "Zoom software"),
                    ("vc", "Vocal command software"),
                    ("ds", "DYS Disorder software"),
                    ("vk", "Virtual keyboard"),
                    ("an", "Adapted navigation dispositive"),
                    ("ek", "Exclusive keyboard navigation"),
                    ("ot", "Other"),
                ],
                max_length=2,
                verbose_name="Assistive technology used",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="browser",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ff", "Firefox"),
                    ("ch", "Chrome"),
                    ("ie", "Internet Explorer"),
                    ("me", "Microsoft Edge"),
                    ("ot", "Other"),
                    ("dn", "Don't know"),
                ],
                max_length=2,
                verbose_name="Browser",
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="inaccessibility_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ia", "Impossible access"),
                    ("ad", "Access possible by bypass but difficult"),
                    (
                        "ra",
                        "Random access, sometimes it works and sometimes it does not",
                    ),
                ],
                max_length=2,
                verbose_name="Inaccessibility level",
            ),
        ),
    ]
