# Generated by Django 3.1.8 on 2021-04-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0008_auto_20210421_0835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vu", "Yes, very urgent: need a quick answer"),
                    ("mu", "Moderately, I can wait, but not too long"),
                    (
                        "nu",
                        "Not urgent at all, but would like a solution as soon as possible",
                    ),
                ],
                max_length=2,
                verbose_name="Whether the request is urgent and has to be handled as quick as possible",
            ),
        ),
    ]
