# Generated by Django 3.1.8 on 2021-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0010_auto_20210421_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="mobile_app_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("is", "iOS"),
                    ("ad", "Android"),
                    ("wp", "Windows phone"),
                    ("ot", "Other"),
                ],
                max_length=2,
                verbose_name="The used mobile app platform",
            ),
        ),
    ]
