# Generated by Django 3.1.8 on 2021-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0011_auto_20210428_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediationrequest",
            name="first_name",
            field=models.CharField(
                max_length=255, verbose_name="First name / username"
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="mediationrequest",
            name="step_description",
            field=models.TextField(blank=True, verbose_name="Step description"),
        ),
    ]
