# Generated by Django 3.1.8 on 2021-04-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0012_auto_20210430_0948"),
        ("mediations", "0011_auto_20210423_1428"),
    ]

    operations = []
