# Generated by Django 3.1.10 on 2021-07-06 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0018_auto_20210617_1224"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediationrequest",
            name="request_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="The date time when the request was made",
            ),
        ),
    ]
