# Generated by Django 3.1.10 on 2021-08-23 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0025_auto_20210820_1735"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracereport",
            name="contact_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date of the contact"
            ),
        ),
        migrations.AlterField(
            model_name="tracereport",
            name="trace_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ca", "Call"),
                    ("ma", "E-mail"),
                    ("le", "Letter"),
                    ("ot", "Autre"),
                ],
                max_length=2,
                verbose_name="The contact type",
            ),
        ),
    ]
