# Generated by Django 4.0.8 on 2022-11-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TraceReport",
        ),
    ]
