# Generated by Django 3.1.10 on 2021-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20210930_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last name"
            ),
        ),
    ]
