# Generated by Django 3.1.8 on 2021-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20201210_1710"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=255, verbose_name="First name / username"
            ),
        ),
    ]
