# Generated by Django 4.0.8 on 2022-11-02 17:03

import connect_access.apps.mediations.trace_report.abstract_models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mediations", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Public identifier",
                    ),
                ),
                (
                    "contact_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date of the contact",
                    ),
                ),
                (
                    "trace_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ca", "Call"),
                            ("ma", "E-mail"),
                            ("le", "Letter"),
                            ("ot", "Other"),
                        ],
                        max_length=2,
                        verbose_name="The contact type",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cp", "Complainant"),
                            ("md", "Mediator"),
                            ("or", "Organization (partner)"),
                            ("eo", "External organization"),
                            ("ot", "Other"),
                        ],
                        max_length=2,
                        verbose_name="Sender type",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Name of the sender(s)"
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cp", "Complainant"),
                            ("md", "Mediator"),
                            ("or", "Organization (partner)"),
                            ("eo", "External organization"),
                            ("ot", "Other"),
                        ],
                        max_length=2,
                        verbose_name="Recipient type",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Name of the recipient(s)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        verbose_name="The main text describing what has happened during the contact",
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        blank=True,
                        upload_to=connect_access.apps.mediations.trace_report.abstract_models.trace_directory_path,
                        verbose_name="Attached file",
                    ),
                ),
                (
                    "mediation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mediations.mediationrequest",
                        verbose_name="The mediation request to which this trace is linked",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace report",
                "verbose_name_plural": "Trace reports",
                "abstract": False,
            },
        ),
    ]
