# Generated by Django 4.0.8 on 2023-09-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trace_report", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TraceReport",
        ),
    ]
