#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


cd /app/backend
python manage.py compilescss
python manage.py collectstatic --noinput
python manage.py compilemessages

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app/backend
