log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  flower:
    address: ":5555"

http:
  routers:
    web-router:
      rule: "HostRegexp(`{any:.+}`)"

      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    flower-secure-router:
      rule: "HostRegexp(`{any:.+}`)"
      entryPoints:
        - flower
      service: flower

    web-media-router:
      rule: "HostRegexp(`{any:.+}`) && PathPrefix(`/media/`)"
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
