name: Frontend tests

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
        working-directory: ./frontend
      - run: yarn lint
        working-directory: ./frontend

  test_frontend:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f local.yml build
      - run: docker-compose -f local.yml run --rm -w /app/frontend django yarn install
      - run: docker-compose -f local.yml up -d
      - run: docker-compose -f local.yml run -w /app/frontend django yarn test --watchAll=false --ci
